name: testing ubuntu impish amd64

on:
  push:
    branches: master
    paths:
      - 'stages/testing/*'
      - '.github/workflows/build-debian.yml'
      - '.github/workflows/build-pkg-workflow.yml'
      - 'distros/ubuntu/impish/impish-model.yml'
      - 'distros/ubuntu/impish/setup.sh'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    uses: regolith-linux/package-repo/.github/workflows/build-pkg-workflow.yml@master
    with:
      model-name: regolith-2.0-package-model.json
      distro-name: ubuntu
      codename: impish
      arch: amd64
      stage: testing
    secrets:
      PACKAGE_PRIVATE_KEY: ${{ secrets.PACKAGE_PRIVATE_KEY }}
