name: unstable debian bullseye arm64

on:
  push:
    branches: master
    paths:
      - 'stages/unstable/**'
      - '.github/workflows/build-unstable-debian-bullseye-arm64.yml'
      - '.github/workflows/build-pkg-workflow-amd64.yml'
      - 'distros/unstable/debian/bullseye/bullseye-model.yml'
      - 'distros/unstable/debian/bullseye/setup.sh'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    uses: regolith-linux/package-repo/.github/workflows/build-pkg-workflow-arm64.yml@master
    with:
      model-name: regolith-2.0-package-model.json
      distro-name: debian
      codename: bullseye
      arch: arm64
      stage: unstable
    secrets:
      PACKAGE_PRIVATE_KEY: ${{ secrets.PACKAGE_PRIVATE_KEY }}
