name: Debian Bullseye amd64

on:
  push:
    branches: master
    paths:
      - 'regolith-2.0-package-model.json'
      - '.github/workflows/debian.yml'
      - 'distros/debian/*'
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    uses: regolith-linux/package-repo/.github/workflows/build-pkg-workflow.yml@master
    with:
      model-path: regolith-2.0-package-model.json
      distro-name: debian
      codename: bullseye
      arch: amd64
    secrets:
      PACKAGE_PRIVATE_KEY: ${{ secrets.PACKAGE_PRIVATE_KEY }}
