name: regolith-desktop is installable

on: 
  push:
    branches: master
  workflow_dispatch:

jobs:
  test-ubuntu-amd64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stage: [unstable, testing ] #TODO add 'release' 
    steps:
      - name: install
        run: |
          set -x
          set -e
          wget -qO - https://regolith-linux.github.io/package-repo/regolith.key | sudo apt-key add -
          export STAGE=${{ matrix.node }} 
          export DISTRO=ubuntu    # choose either 'ubuntu' or 'debian' here depending on system installing into
          export CODENAME=focal # choose either 'focal' or 'impish' for ubuntu or 'bullseye' for debian
          export ARCH=amd64       # choose either 'amd64' or 'arm64'
          echo "deb [arch=amd64] https://regolith-linux.github.io/package-repo/$STAGE/$DISTRO/$CODENAME/$ARCH $CODENAME main" | sudo tee /etc/apt/sources.list.d/regolith.list
          sudo apt update
          sudo apt install -y regolith-desktop