name: regolith-desktop is installable

on: 
  push:
    branches: master
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stage: [ unstable, testing ] #TODO add 'release' 
        arch: [ amd64 ]
        distro: [ ubuntu ]
        codename: [ focal ]
    steps:
      - name: Test Ubuntu 20.04
        uses: kgilmer/test-ubuntu-20.04-action@v1.1.2
        with:
          apt-key-url: https://regolith-linux.github.io/package-repo/regolith.key
          apt-repo-line: "deb [arch=${{ matrix.arch }}] https://regolith-linux.github.io/package-repo/${{ matrix.stage }}/${{ matrix.distro }}/${{ matrix.codename }}/${{ matrix.arch }} ${{ matrix.codename }} main"
          target-package: "regolith-desktop"
          