name: regolith-desktop is installable

on: 
  push:
    branches: master
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, self-hosted]
        stage: [unstable, testing ] #TODO add 'release' 
    steps:
      - name: setup
        run: |
          wget https://raw.githubusercontent.com/regolith-linux/package-repo/master/.github/scripts/install-regolith.sh
          chmod u+x install-regolith.sh
      - name: install
        run: |
          set -x
          ./install-regolith.sh ${{ matrix.stage }} ubuntu focal amd64
          