name: regolith-desktop is installable

on: 
  push:
    branches: master
  workflow_dispatch:

jobs:
  test-ubuntu-amd64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        stage: [unstable, testing ] #TODO add 'release' 
    steps:
      - name: install
        run: |
          set -x
          pwd
          find .
          "${GITHUB_WORKSPACE}/.github/scripts/install-regolith.sh ${{ matrix.stage }} ubuntu focal amd64"
          